/**
 @author        : Anshul Kanaujia 
 @created date  : 04/05/2023
 @last modified : ==================
 @cmp           : ==================
 @test Class    : AddToCart_Test
 @desc          : For all kind of operations, that we are using in Ecommerce
 
 @imp note      : ====================== Please do not change this class without my permession ===================
*/


public without sharing class AddToCart {
    
    public AddToCart() {

    }

    
 


}